export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const ADD_TO_CART = 'ADD_TO_CART';
export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const UPDATE_QUANTITY_CART_ITEM = 'UPDATE_QUANTITY_CART_ITEM';
export const SEARCH = 'SEARCH';
export const SEARCH_KEYWORD = 'SEARCH_KEYWORD';
export const FETCH_PRODUCTS_IN_SEARCH = 'FETCH_PRODUCTS_IN_SEARCH';
export const FILTER_IN_SEARCH = 'FILTER_IN_SEARCH';



